name: My Jekyll Theme
url: # localhost:4000 
baseurl: # /hackerearth 


name: Parth Krishna
email: thenerdsuperuser@gmail.com


markdown: kramdown
highlighter: redcarpet
#highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
