name: Parth Krishna
email: thenerdsuperuser@gmail.com


url: https://thenerdsuperuser.xyz

position: SDE
organization: Invide Labs
image: ./assets/images/profile.png
twitter: vimoveremacs
github: thenerdsuperuser
linkedin: parthkrishna
spotify: normalguyincollege
resume: https://drive.google.com/file/d/1-Mf4HVkdS8gdzVSRHry3ku2TAlFamRQK/view

pages_list:       
  Log: '/hackerearth'
  Archive: '/insta'

markdown: kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
