name: Parth Krishna
email: thenerdsuperuser@gmail.com


url: https://thenerdsuperuser.xyz

position: SDE
organization: Invide Labs
image: ./assets/images/profile.webp
twitter: vimoveremacs
linkedin: parthkrishna
spotify: https://open.spotify.com/user/7u03qd6wd3c6r2jgxq7xsxmvf?si=NrdihBnWS9uSQCqtPGKNaw
resume: https://drive.google.com/file/d/1-Mf4HVkdS8gdzVSRHry3ku2TAlFamRQK/view

sha: 2873bb1

pages_list:
  Notes: '/notes'
  Log: '/hackerearth'

markdown: kramdown
highlighter: rouge

collections:
  notes:
    output: true
    permalink: /notes/:path/
    collections_dir: coll

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
