name: minimalist
url: thenerdsuperuser.xyz 
baseurl: # 


name: Parth Krishna
email: thenerdsuperuser@gmail.com

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:

      position: SDE
      organization: Invide Labs
      image: ./assets/images/profile.png
      twitter: https://twitter.com/vimoveremacs
      github: https://github.com/thenerdsuperuser
      linkedin: https://linkedin.com/in/parthkrishna

      layout: "home"
      author: "Parth"

markdown: kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
