name: Update Footer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Create local changes
        env:
            myREPO: ${{ github.repository }}
            mySHA: ${{ github.sha }}
        run: sed -i "s/$(awk '/sha/ {print $2}' _config.yml)/$mySHA/" _config.yml
      - uses: pCYSl5EDgo/cat@master
        id: hello
        with:
          path: _config.yml

      - run: echo $TEXT
        env:
          TEXT: ${{ steps.hello.outputs.text  }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Updated _config.yml with full link to commit SHA." -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
